#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# File main

import cgitb; cgitb.enable()
import cgi
import TeamOhtml
import page_functions
from page_functions import *
from TeamOhtml import *
import MySQLdb

db = MySQLdb.connect(host="localhost", port=3306, user="root", passwd="", db="PhotoBomb")

cursor = db.cursor()

form = cgi.FieldStorage()
email = form.getfirst('email', "")
user_id = None
if cursor.execute('SELECT ID FROM User WHERE email="%s";' % email) >= 1:
    user_id = cursor.fetchone()
if cursor.execute('SELECT firstname FROM User WHERE email="%s";' % email) >= 1:
    user_name = cursor.fetchone()[0]
if user_id:
    print beginHTML() + """
    %s
    <tr>
    <table cellpadding=5 table cellspacing="10" width=35%%>
    <table align="center">
    <td><a href=home>My Home</a></td>
    </tr>
    </table>
    </br>
    <align="middle">
    <img src="/wedding-photobomb-1.jpg" style="width:500px;height:400px">
    """ % greet_user(user_name) + endHTML()
else:
    print beginHTML() + """
    An error has occurred, <a href=welcome>click here</a> to continue.
    """ + endHTML()
db.commit()
db.close()
