#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# File main

import cgitb; cgitb.enable()
import cgi, Cookie, os
import TeamOhtml
import page_functions
from page_functions import *
from TeamOhtml import *
import MySQLdb

db = MySQLdb.connect(host="localhost", port=3306, user="root", passwd="", db="PhotoBomb")

cursor = db.cursor()
form = cgi.FieldStorage()
email = form.getfirst('session', "")
user_id = None


cookie_string = os.environ.get('HTTP_COOKIE')

if not cookie_string and not email:
    print beginHTML() + """
    %s
    Uh, oh! An error has occurred, <a href=welcome>click here</a> to continue.
    """ %cookie_string + endHTML()
else:
    if cursor.execute('SELECT ID FROM User WHERE email="%s";' % email) >= 1:
        user_id = cursor.fetchone()
    if cursor.execute('SELECT firstname FROM User WHERE email="%s";' % email) >= 1:
        user_name = cursor.fetchone()[0]
    if user_id:
            print beginHTML() + """
            %s
            %s
            </br>
            <align="middle">
            <img src="/wedding-photobomb-1.jpg" style="width:500px;height:400px">
            """ % (greet_user(user_name), top_links(email))+ endHTML()
    else:
        print beginHTML() + """
        An error has occurred, <a href=welcome>click here</a> to continue.
        """ + endHTML()
db.commit()
db.close()
