#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# File main

import cgitb; cgitb.enable()
import TeamOhtml
from TeamOhtml import *
import cgi

form = cgi.FieldStorage()
email = form.getfirst('session', '')
user_name = ''
user_id = None
result = ''
imgur = ''
import os
import MySQLdb

db = MySQLdb.connect(host='localhost', port=3306, user='root', passwd='',
                     db='PhotoBomb')
cursor = db.cursor()

#get file name:
fileitem = form['filename']
if cursor.execute('SELECT firstname FROM User WHERE email="%s";' % email) >= 1:
        user_name = cursor.fetchone()[0]
if cursor.execute('SELECT ID FROM User WHERE email="%s";' % email) >= 1:
        user_id = cursor.fetchone()
    

if fileitem.filename:
    fn = os.path.basename(fileitem.filename)
    file_root = '/var/www/html'
    file_path = '/images/%s' % (fn[:-4] + email + fn[-4:])
    file_savepath = file_root + file_path
    message = file_savepath + '\n'
    message += os.getcwd() + '\n'
    os.chdir(file_root + '/images/')
    message += os.getcwd() + '\n'
    with open(file_savepath, 'wb') as f:
        while 1:
            chunk = fileitem.file.read(1024)
            if not chunk:
                break
            f.write(chunk)
    message += '<img src="' + file_path + '" width=300 height=300/>\n'
    message += 'The file "' + fn + '" was uploaded successfully'
    cursor.execute(
else:
    message = 'No file was uploaded'

print beginHTML() + """
%s
You cannot upload something, because I don't feel like it today...
""" % message + endHTML();

db.commit()
db.close()
