#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# File main


import cgitb; cgitb.enable()
import cgi
import MySQLdb
import TeamOhtml
from TeamOhtml import *

# create a database within the code. it will allow access to the database
# for the site
db = MySQLdb.connect(host="localhost", port=3306, user="root", passwd="", db="PhotoBomb")

#create a cursor for the database, it's necessary
cursor = db.cursor()
# get the form, and check if everything is okay
# if form is empty, use normal signup page.
form = cgi.FieldStorage()
firstname = form.getfirst('firstname', "")
lastname = form.getfirst('lastname', "")
email = form.getfirst('email', "")
password = form.getfirst('password', "")
passcheck = form.getfirst('passcheck', "")
error_message = ""
if firstname == lastname and lastname == email and email == password and \
   password == passcheck and passcheck == "":
    error_message = " "
else:
    if password != passcheck:
        error_message += "The password does not match password check!</br>"
    if len(password) < 6:
        error_message += "Password must be atleast 6 characters in length!</br>"
    if (cursor.execute('SELECT ID from User where email="%s";' % email) >= 1):
        test = cursor.fetchone()
        error_message += "This email already exists!</br>"
        

if error_message:
    print beginHTML() + r"""
    <font size="2" color="red">%s</font>
    <table>
    <form method='post' action="signup">
    <tr>
    <td>First Name</td>
    <td><input type='text' value='' name='firstname' /> </td></tr>
    <tr>
    <td>Last Name</td>
    <td><input type='text' value='' name='lastname' /> </td></tr>
    <tr>
    <td>Email</td>
    <td><input type='text' value='' name='email' /> </td></tr>
    <tr><td>Password</td>
    <td><input type='password' value='' name='password' /> </td></tr>
    <tr>
    <td>Confirm Password</td>
    <td><input type='password' value='' name='passcheck' /> </td></tr>
    <tr>
    <td></td><td align=right><input type='submit'/></td></tr>
    </form>
    </table>

    <a href="login"> Already have an account? Click here to login! </a>
    """ % error_message + endHTML()
else:
    #print test
    cursor.execute('insert User set firstname="%s", lastname="%s", email="%s", password="%s";' % (firstname, lastname, email, password))
    user_id = None
    if cursor.execute('SELECT ID FROM User WHERE email="%s";' % email) >= 1:
        user_id = cursor.fetchone()
    cursor.execute('insert Album set user_ID="%s", name="%s"' % (user_id, 'main'))
    print beginHTML() + r"""
    Signup successful! Yeah!!!
    <a href="login"> Click here to continue.</a>
    """ + endHTML()
db.commit()
db.close()
