#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# File: viewListOfUser

import cgitb; cgitb.enable()
import page_functions
import TeamOhtml
from TeamOhtml import *
import cgi
form = cgi.FieldStorage()
username = form.getfirst('session', '')
result = ''
if username != '':
    result = ', ' + username

import MySQLdb
dbList = []
listOfUsers = ''
db = MySQLdb.connect(host='localhost', port=3306,
                     user='root', passwd='', db='PhotoBomb')
cursor = db.cursor()
if cursor.execute('SELECT email FROM User') >= 1:
    dbList = cursor.fetchall()
if dbList:
    listOfUsers = ''
    listOfUsers = '<table>\n'
    for item in dbList:
        if item[0] != username:
            listOfUsers += '<tr><td><a href=viewPhotos?session=%s&view=%s>' % (username,item[0])
            listOfUsers += '%s</a></td></tr>\n' % item[0]
    listOfUsers += '</table>\n'
print beginHTML() + """
%s
%s
""" % (top_links(username), listOfUsers) + endHTML()
db.close()
