#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# File main

#import cgitb; cgitb.enable()
import TeamOhtml
from TeamOhtml import *

print beginHTML() + """
<tr>
<table cellpadding=5 table cellspacing="10" width=35%%>
<table align="center">
<td><a href=welcome>Home</a></td>
<td><a href=signup>Sign up</a></td>
<td><a href=login>Log in</a></td>
</tr>
</table>
<center>
<h2>Welcome to Photo Bomb!!!</h2>
</center>
<p>
<center>
<align="middle">
<img src="/wedding-photobomb-1.jpg" style="width:500px;height:400px">
</center>
<p><p><p><p>
<center>
<p> Need a place to store your photos??? </p>
<p> TRY PHOTO-BOMB TODAY! </p>
</center>
</p></p></p></p>
""" + endHTML()
